### ISSUE TITLE
Add a way to only include specific classes

### ISSUE THREAD

**Issue by Symbai** [BadRyuner/MonoTrainer#2]
The generated SDK library is huge, ~25mb in my case. It contains lots of code I am not interesting in. I think if we could have a way to only include specific classes it would be MUCH smaller. Is that possible?

**Comment by BadRyuner** [comment]
Yes, it is possible. I will try to add a whitelist for classes.

**Comment by BadRyuner** [comment]
Removed the creation of proxy types for the entire mscorlib by default. Also added the ability to create proxy types for certain classes. This doesn't work very well because it creates default types for parent classes and classes that are used in fields/methods. However, this can reduce a couple of megabytes. In my example for your game it turned out to be 6.5 mb.

**Comment by Symbai** [comment]
Thank you, I'll try it out on some more games. This is an awesome project, nice job!

**Comment by Symbai** [comment]
fyi, I pulled your changes but I cannot build SDK generator because VS claims `Arguments` is not declared / found. Did you forgot to include something in your commit?

**Comment by BadRyuner** [comment]
https://github.com/BadRyuner/MonoTrainer/blob/master/SDKGenerator/Program.cs#L44
